### ISSUE TITLE
slug function does not accept partial options object

### ISSUE THREAD

**Issue by pskfyi** [dunosaurs/slug#3]
Hello and sorry to be creating your first GH issue. Thank you for the library.

When trying to use v1.0.0 in the manner shown [here](https://github.com/dunosaurs/slug/blob/v1.0.0/mod.ts#L31), passing a partial options object, I am encountering a TS compiler error because the `options` argument ([here](https://github.com/dunosaurs/slug/blob/v1.0.0/mod.ts#L43)) is typed as `string | SlugOptions` rather than `string | Partial<SlugOptions>` as would be expected given that this input is merged with the default options object [here](https://github.com/dunosaurs/slug/blob/v1.0.0/mod.ts#L57).

<img width="747" alt="Screen Shot 2022-11-27 at 6 33 08 AM" src="https://user-images.githubusercontent.com/47710574/204141028-305a7463-ea18-473a-9346-0d737cb7f857.png">

I encountered other issues while addressing this. In the code, `SlugOptions` is not exported so I was not able to easily work around the issue using `{ lower: true } as SlugOptions`. And in the repo, I could not find a license file or a CONTRIBUTING.md file. Please let me know if you would like me to create separate issues for any of these.

I take no offense if you decide to delete this issue or if you do not reply. Just figured I'd give the feedback. Thanks again for the library.

**Comment by lino-levan** [comment]
Thank you for the issue. I will fix this now.

**Comment by lino-levan** [comment]
Fixed by https://github.com/dunosaurs/slug/commit/13c628ef8f67a14b5fd3071c91ed86461cd9e79f. Thanks for the report!

**Comment by lino-levan** [comment]
I should also say that I added a license + exported SlugOptions

**Comment by pskfyi** [comment]
Thank you for the quick turnaround, new releases, and permissive license! 🥂
