### ISSUE TITLE
remove option is not implemented

### ISSUE THREAD

**Issue by pskfyi** [dunosaurs/slug#4]
Thanks again for the help on the previous issue! I found one more issue: the `remove` option doesn't do anything. Here's a search for `remove` in the repo: https://github.com/dunosaurs/slug/search?q=remove

**Comment by lino-levan** [comment]
I don't know how that slipped by. We should really be having a lot more test cases. I have fixed this + a few embarrassing typos in `v1.1.0`.

Thank you for these issues!

**Comment by pskfyi** [comment]
Hey no worries. Thanks for another quick turnaround! You've unblocked me to make significant progress in my weekend project.

**Comment by lino-levan** [comment]
No worries! I really appreciate your feedback!
